name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - run: |
          sudo apt update
          sudo apt install -y cmake
          cmake --version
          sudo apt install -y nvidia-cuda-dev

      - name: free up space
        run: |
          bash <(curl -s https://raw.githubusercontent.com/apache/flink/02d30ace69dc18555a5085eccf70ee884e73a16e/tools/azure-pipelines/free_disk_space.sh)
          sudo rm -rf /opt/hostedtoolcache
          df -h

      - uses: christianrauch/ros-deb-builder-action@network
        with:
          ROS_DISTRO: humble
          DEB_DISTRO: jammy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
