name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
      options: --privileged
      volumes:
        - /mnt:/tmp

    continue-on-error: true

    steps:
      - run: |
          chmod 777 /tmp
          df -h

      - name: install dependencies
        run: |
          apt update
          apt install -y sudo
          sudo apt install -y cmake
          cmake --version
          sudo apt install -y tree curl lsb-release software-properties-common

      # - name: free up space
      #   shell: bash
      #   run: |
      #     bash <(curl -s https://raw.githubusercontent.com/apache/flink/02d30ace69dc18555a5085eccf70ee884e73a16e/tools/azure-pipelines/free_disk_space.sh)
      #     sudo rm -rf /opt/hostedtoolcache
      #     df -h

      # - run: |
      #     pwd
      #     tree

      - run: |
          usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $(whoami)

      - name: list repos
        run: |
          cat /etc/apt/sources.list

      - uses: christianrauch/ros-deb-builder-action@network
        with:
          ROS_DISTRO: humble
          DEB_DISTRO: jammy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          SBUILD_CONF: "$extra_repositories = [ 'deb [trusted=yes] http://archive.ubuntu.com/ubuntu jammy multiverse restricted' ];"
          # keys for GCC 10:
          # https://github.com/ros/rosdistro/pull/39349
          ROSDEP_SOURCE: "yaml https://raw.githubusercontent.com/christianrauch/rosdistro/g%2B%2B-10/rosdep/base.yaml"
          # WORKING_DIRECTORY: /mnt

      - name: check free space
        if: always()
        run: |
          df -h
